(async()=>{
'use strict';
if(window.AANYA_PDF){const raw=atob(window.AANYA_PDF),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);const url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));document.querySelectorAll('.book-link').forEach(a=>a.href=url);}
const $=id=>document.getElementById(id),I=window.AANYA_I18N;
let pages,activeCategory=null,current=0;const visited=new Set(),dialog=$('reader');
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function switchTab(original){$('original-panel').hidden=!original;$('reading-panel').hidden=original;for(const [id,yes]of[['original-tab',original],['reading-tab',!original]]){$(id).classList.toggle('active',yes);$(id).setAttribute('aria-selected',String(yes));$(id).tabIndex=yes?0:-1;}}
function display(i,keepTab=false){const original=keepTab&&!$('original-panel').hidden;current=(i+pages.length)%pages.length;const source=pages[current],p=I.topic(source),u=I.ui;visited.add(p.id);$('reader-title').textContent=p.title;$('reader-category').textContent=I.category(p.category);$('story-intro').textContent=p.intro;$('reader-image').src=p.notebook||p.original;$('reader-image').alt=u.bright+p.title+(I.lang==='en'?' (handwritten in Swedish)':'');$('original-image').src=p.original;$('original-image').alt=u.original+p.title;$('facts').replaceChildren(...p.facts.map(x=>el('li',x)));$('editor-note').textContent=p.note||'';const box=$('imagination');box.replaceChildren();box.hidden=!p.imagination;if(p.imagination){box.append(el('h3',p.imagination.title),el('p',p.imagination.intro));p.imagination.items.forEach(x=>{const row=el('div',undefined,'future-item');row.append(el('strong',x.year),el('span',x.text));box.append(row);});}$('counter').textContent=(current+1)+' '+u.of+' '+pages.length;switchTab(original);if(!keepTab)dialog.scrollTop=0;render();}
function render(){const u=I.ui,q=$('search').value.trim().toLocaleLowerCase(I.lang);const filtered=pages.filter(source=>{const p=I.topic(source);return(activeCategory===null||p.category===activeCategory)&&[p.title,I.category(p.category),p.intro,...p.facts].join(' ').toLocaleLowerCase(I.lang).includes(q);});$('topics').replaceChildren();filtered.forEach(source=>{const p=I.topic(source),i=pages.indexOf(source),b=el('button',undefined,'card');b.style.setProperty('--pastel',['#ebdfef','#e1edf0','#f5e3de','#e6ecd9'][i%4]);b.setAttribute('aria-label',u.open+p.title);const img=el('img');img.src=p.src;img.alt=u.sketch+p.title;img.loading='lazy';b.append(img,el('small',String(i+1).padStart(2,'0')+' / '+I.category(p.category)),el('h3',p.title),el('p',p.intro),el('span',u.read,'read'));if(visited.has(p.id))b.append(el('span',u.seen,'seen'));b.addEventListener('click',()=>{display(i);dialog.showModal();});$('topics').append(b);});if(!filtered.length)$('topics').append(el('p',u.none,'status'));$('count').textContent=filtered.length+' '+u.of+' '+pages.length+' '+u.pages+' · '+visited.size+' '+u.discovered;}
function filters(){const cats=[null,...new Set(pages.map(p=>p.category))];$('filters').replaceChildren();cats.forEach(cat=>{const b=el('button',cat===null?I.ui.all:I.category(cat));const selected=cat===activeCategory;b.setAttribute('aria-pressed',String(selected));b.classList.toggle('active',selected);b.addEventListener('click',()=>{activeCategory=cat;filters();render();});$('filters').append(b);});}
function bookCount(){const u=I.ui;$('book-count').textContent=pages.length+' '+u.topics+' · '+(pages.length+2+Math.ceil(pages.length/16))+' '+u.bookPages+' · '+u.keep;}
try{if(window.AANYA_CONTENT)pages=window.AANYA_CONTENT;else{const r=await fetch('content.json',{cache:'no-cache'});if(!r.ok)throw new Error('Content unavailable');pages=await r.json();}if(!Array.isArray(pages)||!pages.length)throw new Error('No topics');filters();bookCount();render();if(location.hash.startsWith('#sida-')){const i=pages.findIndex(p=>String(p.id)===location.hash.slice(6));if(i>=0){display(i);dialog.showModal();}}
}catch(e){$('topics').replaceChildren(el('p',I.ui.error,'status'));document.addEventListener('aanya-language-change',()=>$('topics').replaceChildren(el('p',I.ui.error,'status')));return;}
document.addEventListener('aanya-language-change',()=>{filters();bookCount();if(dialog.open)display(current,true);else render();});
$('search').addEventListener('input',render);$('close').addEventListener('click',()=>dialog.close());$('prev').addEventListener('click',()=>display(current-1));$('next').addEventListener('click',()=>display(current+1));$('reading-tab').addEventListener('click',()=>switchTab(false));$('original-tab').addEventListener('click',()=>switchTab(true));document.querySelector('[role="tablist"]').addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const yes=$('original-panel').hidden;switchTab(yes);$(yes?'original-tab':'reading-tab').focus();}});document.addEventListener('keydown',e=>{if(dialog.open&&!e.target.closest('[role="tablist"]')&&e.target.tagName!=='INPUT'){if(e.key==='ArrowRight')display(current+1);if(e.key==='ArrowLeft')display(current-1);}});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
})();
