(async()=>{
'use strict';
if(window.AANYA_PDF){const raw=atob(window.AANYA_PDF),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);const url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));document.querySelectorAll('.book-link').forEach(a=>a.href=url);}
const $=id=>document.getElementById(id);let pages,activeCategory='Alla',current=0;const visited=new Set(),dialog=$('reader');
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function switchTab(original){$('original-panel').hidden=!original;$('reading-panel').hidden=original;for(const [id,yes]of[['original-tab',original],['reading-tab',!original]]){$(id).classList.toggle('active',yes);$(id).setAttribute('aria-selected',String(yes));$(id).tabIndex=yes?0:-1;}}
function display(i){current=(i+pages.length)%pages.length;const p=pages[current];visited.add(p.id);$('reader-title').textContent=p.title;$('reader-category').textContent=p.category;$('story-intro').textContent=p.intro;$('reader-image').src=p.notebook||p.original;$('reader-image').alt='Ljusare presentation av Aanyas anteckningssida om '+p.title;$('original-image').src=p.original;$('original-image').alt='Originalfotografi: '+p.title;$('facts').replaceChildren(...p.facts.map(x=>el('li',x)));$('editor-note').textContent=p.note||'';const box=$('imagination');box.replaceChildren();box.hidden=!p.imagination;if(p.imagination){box.append(el('h3',p.imagination.title),el('p',p.imagination.intro));p.imagination.items.forEach(x=>{const row=el('div',undefined,'future-item');row.append(el('strong',x.year),el('span',x.text));box.append(row);});}$('counter').textContent=(current+1)+' av '+pages.length;switchTab(false);dialog.scrollTop=0;render();}
function render(){const q=$('search').value.trim().toLocaleLowerCase('sv');const filtered=pages.filter(p=>(activeCategory==='Alla'||p.category===activeCategory)&&[p.title,p.category,p.intro,...p.facts].join(' ').toLocaleLowerCase('sv').includes(q));$('topics').replaceChildren();filtered.forEach(p=>{const i=pages.indexOf(p),b=el('button',undefined,'card');b.style.setProperty('--pastel',['#ebdfef','#e1edf0','#f5e3de','#e6ecd9'][i%4]);b.setAttribute('aria-label','Öppna '+p.title);const img=el('img');img.src=p.src;img.alt='Blyertssketch: '+p.title;img.loading='lazy';b.append(img,el('small',String(i+1).padStart(2,'0')+' / '+p.category),el('h3',p.title),el('p',p.intro),el('span','Öppna anteckningssidan ↗','read'));if(visited.has(p.id))b.append(el('span','✧ Du har bläddrat här','seen'));b.addEventListener('click',()=>{display(i);dialog.showModal();});$('topics').append(b);});if(!filtered.length)$('topics').append(el('p','Ingen sida matchar din sökning. Prova ett annat ord.','status'));$('count').textContent=filtered.length+' av '+pages.length+' sidor · '+visited.size+' upptäckta under ditt besök';}
try{if(window.AANYA_CONTENT)pages=window.AANYA_CONTENT;else{const r=await fetch('content.json',{cache:'no-cache'});if(!r.ok)throw new Error('Content unavailable');pages=await r.json();}if(!Array.isArray(pages)||!pages.length)throw new Error('No topics');const cats=['Alla',...new Set(pages.map(p=>p.category))];cats.forEach(cat=>{const b=el('button',cat);b.setAttribute('aria-pressed',String(cat==='Alla'));b.classList.toggle('active',cat==='Alla');b.addEventListener('click',()=>{activeCategory=cat;[...$('filters').children].forEach(x=>{const yes=x===b;x.classList.toggle('active',yes);x.setAttribute('aria-pressed',String(yes));});render();});$('filters').append(b);});$('book-count').textContent=pages.length+' ämnen · '+(pages.length+2+Math.ceil(pages.length/16))+' boksidor · Läs, skriv ut och spara';render();if(location.hash.startsWith('#sida-')){const i=pages.findIndex(p=>String(p.id)===location.hash.slice(6));if(i>=0){display(i);dialog.showModal();}}
}catch(e){$('topics').replaceChildren(el('p','Boken kunde inte öppnas här. Använd den fristående HTML-filen eller öppna webbplatsen via en webbserver.','status'));return;}
$('search').addEventListener('input',render);$('close').addEventListener('click',()=>dialog.close());$('prev').addEventListener('click',()=>display(current-1));$('next').addEventListener('click',()=>display(current+1));$('reading-tab').addEventListener('click',()=>switchTab(false));$('original-tab').addEventListener('click',()=>switchTab(true));document.querySelector('[role="tablist"]').addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const yes=$('original-panel').hidden;switchTab(yes);$(yes?'original-tab':'reading-tab').focus();}});document.addEventListener('keydown',e=>{if(dialog.open&& !e.target.closest('[role="tablist"]')&&e.target.tagName!=='INPUT'){if(e.key==='ArrowRight')display(current+1);if(e.key==='ArrowLeft')display(current-1);}});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
})();
